# Generated by Django 5.1.4 on 2025-01-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sex',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, to='products.sex'),
        ),
    ]
