# Generated by Django 5.1.4 on 2025-01-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_typeofproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.typeofproduct'),
        ),
    ]
