# Generated by Django 5.1.4 on 2025-01-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_products_type_productcategory_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.typeofproduct'),
        ),
    ]
