# Generated by Django 5.1.4 on 2025-01-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productcategory_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
